typedef unsigned char	uchar;
typedef unsigned short	ushort;
typedef unsigned int	uint;
typedef unsigned long	ulong;
typedef short		int16;
typedef int		int32;
typedef __int64		int64;
typedef unsigned short	uint16;
typedef unsigned int	uint32;
typedef unsigned __int64 uint64;
