typedef struct ui {
	Buffer *buffer;
	HWND hwnd;
	HWND monoedit;
	TCHAR *filepath;
	/* number of lines displayed */
	WNDPROC med_wndproc;
	int cursor_y;
	int cursor_x;
	int charwidth;
	int charheight;
	HFONT mono_font;
	lua_State *lua;
	uint64 hl_start;
	uint64 hl_len;
	HWND status_bar;
	HINSTANCE instance;
	int npluginfunc;
	char *plugin_name;
	char **plugin_funcname;
	uchar mode;
	uchar cursor_fine_pos;
	uchar readonly;
	HWND treeview;
	uint64 replace_start;
	uchar *replace_buf;
	uint replace_buf_cap;
	uint replace_buf_len;
} UI;
